import React, { useState } from 'react';
import useFetch from '../../hooks/useFetch';

// ─── PDF Generator (client-side, no library needed) ───────────────────────
const generatePrescriptionPDF = (prescription) => {
  const styles = `
    body { font-family: Arial, sans-serif; color: #1e293b; margin: 0; padding: 24px; }
    .header { background: linear-gradient(135deg, #0f766e, #14b8a6); color: white; padding: 24px; border-radius: 8px; margin-bottom: 20px; }
    .header h1 { margin: 0 0 4px; font-size: 1.4rem; }
    .header p { margin: 0; opacity: 0.85; font-size: 0.85rem; }
    .section { margin-bottom: 18px; }
    .section-title { font-size: 0.7rem; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 6px; }
    .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
    .info-row { font-size: 0.9rem; }
    .info-row strong { color: #475569; font-size: 0.78rem; display: block; }
    .diagnosis-box { background: #f0fdfa; border: 1px solid #99f6e4; border-radius: 8px; padding: 12px; font-size: 0.9rem; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #f8fafc; padding: 8px 12px; font-size: 0.78rem; text-align: left; color: #64748b; border-bottom: 2px solid #e2e8f0; }
    td { padding: 8px 12px; font-size: 0.85rem; border-bottom: 1px solid #f1f5f9; }
    .notes-box { background: #fffbeb; border: 1px solid #fde68a; border-radius: 8px; padding: 12px; font-size: 0.85rem; }
    .footer { margin-top: 24px; padding-top: 16px; border-top: 1px dashed #e2e8f0; text-align: center; color: #94a3b8; font-size: 0.75rem; }
  `;
  const apptDate = prescription.appointment?.date
    ? new Date(prescription.appointment.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })
    : 'N/A';

  const html = `
    <!DOCTYPE html>
    <html><head><meta charset="utf-8"><title>Prescription</title>
    <style>${styles}</style></head>
    <body>
      <div class="header">
        <h1>🏥 ${prescription.clinic?.name || 'MediCare Clinic'}</h1>
        <p>${prescription.clinic?.address || ''} ${prescription.clinic?.contactInfo ? '• ' + prescription.clinic.contactInfo : ''}</p>
      </div>

      <div class="section info-grid">
        <div class="info-row"><strong>Patient</strong>${prescription.appointment?.patient?.name || prescription.patient?.name || 'Patient'}</div>
        <div class="info-row"><strong>Doctor</strong>Dr. ${prescription.doctor?.name || ''}</div>
        <div class="info-row"><strong>Date</strong>${apptDate}</div>
        <div class="info-row"><strong>Time Slot</strong>${prescription.appointment?.timeSlot || 'N/A'}</div>
      </div>

      <div class="section">
        <div class="section-title">Diagnosis</div>
        <div class="diagnosis-box">${prescription.diagnosis}</div>
      </div>

      <div class="section">
        <div class="section-title">Prescribed Medicines</div>
        <table>
          <thead><tr><th>#</th><th>Medicine</th><th>Dosage</th><th>Duration</th></tr></thead>
          <tbody>
            ${prescription.medicines.map((m, i) => `
              <tr>
                <td>${i + 1}</td>
                <td>${m.name}</td>
                <td>${m.dosage}</td>
                <td>${m.duration}</td>
              </tr>`).join('')}
          </tbody>
        </table>
      </div>

      ${prescription.notes ? `
      <div class="section">
        <div class="section-title">Additional Notes</div>
        <div class="notes-box">${prescription.notes}</div>
      </div>` : ''}

      <div class="footer">
        Generated by MediCare • ${new Date().toLocaleDateString()} • This is a digitally issued prescription
      </div>
    </body></html>
  `;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.setTimeout(() => { win.print(); }, 500);
};

// ─── Component ────────────────────────────────────────────────────────────
const PrescriptionHistory = () => {
  const { data: prescriptions, loading, error } = useFetch('/patient/prescriptions');
  const [expanded, setExpanded] = useState(null);

  return (
    <div style={{ maxWidth: '800px', margin: '0 auto' }}>
      <div className="animate-fade-in-up" style={{ marginBottom: '24px' }}>
        <h1 style={{ fontSize: '1.5rem', fontWeight: 800, color: '#1e293b', margin: 0 }}>Prescription History</h1>
        <p style={{ color: '#64748b', fontSize: '0.85rem', marginTop: '4px' }}>
          {prescriptions?.length || 0} prescriptions on record
        </p>
      </div>

      {loading && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {[1,2,3].map(i => <div key={i} className="skeleton" style={{ height: '100px', borderRadius: '14px' }} />)}
        </div>
      )}

      {error && (
        <div style={{ padding: '16px', background: '#fef2f2', borderRadius: '12px', color: '#991b1b', border: '1px solid #fecaca', fontSize: '0.9rem' }}>
          {error}
        </div>
      )}

      {!loading && prescriptions?.length === 0 && (
        <div style={{ textAlign: 'center', padding: '60px 0' }}>
          <div style={{ fontSize: '3rem', marginBottom: '12px' }}>📄</div>
          <p style={{ color: '#94a3b8', fontStyle: 'italic' }}>No prescriptions found yet.</p>
        </div>
      )}

      <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
        {prescriptions?.map((rx, idx) => {
          const isOpen = expanded === rx._id;
          const apptDate = rx.appointment?.date
            ? new Date(rx.appointment.date).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
            : 'N/A';

          return (
            <div key={rx._id} className={`animate-fade-in-up stagger-${Math.min(idx + 1, 6)}`} style={{
              background: 'white', borderRadius: '14px',
              boxShadow: '0 2px 10px rgba(0,0,0,0.05)', border: `1px solid ${isOpen ? '#99f6e4' : '#f1f5f9'}`,
              overflow: 'hidden', transition: 'all 0.3s ease'
            }}>
              {/* Header row */}
              <div
                onClick={() => setExpanded(isOpen ? null : rx._id)}
                style={{
                  padding: '18px 20px', display: 'flex', justifyContent: 'space-between',
                  alignItems: 'center', flexWrap: 'wrap', gap: '10px', cursor: 'pointer',
                  background: isOpen ? 'linear-gradient(135deg, rgba(15,118,110,0.04), rgba(20,184,166,0.04))' : 'white',
                  transition: 'background 0.2s ease'
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{
                    width: '44px', height: '44px', borderRadius: '12px',
                    background: 'linear-gradient(135deg, #d1fae5, #a7f3d0)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '1.3rem'
                  }}>💊</div>
                  <div>
                    <h4 style={{ fontWeight: 700, color: '#1e293b', margin: 0, fontSize: '0.95rem' }}>
                      Dr. {rx.doctor?.name}
                    </h4>
                    <p style={{ fontSize: '0.78rem', color: '#64748b', margin: '3px 0 0', display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                      <span>{apptDate}</span>
                      {rx.appointment?.timeSlot && <span>at {rx.appointment.timeSlot}</span>}
                      {rx.clinic?.name && <span>• {rx.clinic.name}</span>}
                    </p>
                  </div>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <span style={{
                    fontSize: '0.75rem', fontWeight: 600, color: '#0f766e',
                    background: '#f0fdfa', border: '1px solid #99f6e4',
                    padding: '3px 10px', borderRadius: '20px'
                  }}>
                    {rx.medicines?.length} medicine{rx.medicines?.length !== 1 ? 's' : ''}
                  </span>
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="2.5" strokeLinecap="round"
                    style={{ transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)', transition: 'transform 0.3s ease' }}>
                    <polyline points="6 9 12 15 18 9"/>
                  </svg>
                </div>
              </div>

              {/* Expandable detail */}
              {isOpen && (
                <div className="animate-fade-in-up" style={{ padding: '0 20px 20px', borderTop: '1px solid #f1f5f9' }}>
                  {/* Diagnosis */}
                  <div style={{ margin: '16px 0 12px' }}>
                    <p style={{ fontSize: '0.72rem', fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '0 0 6px' }}>Diagnosis</p>
                    <div style={{ background: '#f0fdfa', border: '1px solid #99f6e4', borderRadius: '8px', padding: '10px 14px', fontSize: '0.88rem', color: '#134e4a' }}>
                      {rx.diagnosis}
                    </div>
                  </div>

                  {/* Medicines table */}
                  <div style={{ marginBottom: '12px' }}>
                    <p style={{ fontSize: '0.72rem', fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '0 0 8px' }}>Medicines</p>
                    <div style={{ border: '1px solid #f1f5f9', borderRadius: '10px', overflow: 'hidden' }}>
                      <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr', background: '#f8fafc', padding: '8px 14px' }}>
                        {['Medicine', 'Dosage', 'Duration'].map(h => (
                          <span key={h} style={{ fontSize: '0.72rem', fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.04em' }}>{h}</span>
                        ))}
                      </div>
                      {rx.medicines?.map((m, i) => (
                        <div key={i} style={{
                          display: 'grid', gridTemplateColumns: '2fr 1fr 1fr',
                          padding: '10px 14px', borderTop: '1px solid #f1f5f9',
                          background: i % 2 === 0 ? 'white' : '#fafafa'
                        }}>
                          <span style={{ fontWeight: 600, fontSize: '0.88rem', color: '#1e293b' }}>{m.name}</span>
                          <span style={{ fontSize: '0.82rem', color: '#475569' }}>{m.dosage}</span>
                          <span style={{ fontSize: '0.82rem', color: '#475569' }}>{m.duration}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {rx.notes && (
                    <div style={{ marginBottom: '14px' }}>
                      <p style={{ fontSize: '0.72rem', fontWeight: 700, color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', margin: '0 0 6px' }}>Notes</p>
                      <div style={{ background: '#fffbeb', border: '1px solid #fde68a', borderRadius: '8px', padding: '10px 14px', fontSize: '0.85rem', color: '#78350f' }}>
                        {rx.notes}
                      </div>
                    </div>
                  )}

                  {/* Download button */}
                  <button onClick={() => generatePrescriptionPDF(rx)}
                    style={{
                      display: 'flex', alignItems: 'center', gap: '8px',
                      padding: '10px 20px', borderRadius: '10px', border: 'none',
                      background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
                      color: 'white', fontWeight: 700, fontSize: '0.85rem',
                      cursor: 'pointer', fontFamily: 'inherit',
                      boxShadow: '0 4px 12px rgba(99,102,241,0.3)',
                      transition: 'all 0.2s ease'
                    }}
                    onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-1px)'; e.currentTarget.style.boxShadow = '0 6px 16px rgba(99,102,241,0.4)'; }}
                    onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = '0 4px 12px rgba(99,102,241,0.3)'; }}
                  >
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
                      <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/>
                      <polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
                    </svg>
                    Download / Print Prescription
                  </button>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default PrescriptionHistory;
